"""Add isAdmin column to User model

Revision ID: a17ba9b2d506
Revises: e3af7a501d1d
Create Date: 2024-03-14 14:14:30.016989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17ba9b2d506'
down_revision = 'e3af7a501d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdmin', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isAdmin')

    # ### end Alembic commands ###
